kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: ephemeral-single-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    resources: 
      requests:
        memory: 4Gi
        cpu:  1
      limits:
        memory: 4Gi
        cpu: 2
    jvmOptions: 
      -Xms: 4096m
      -Xmx: 4096m
    config:
      inter.broker.protocol.version: "3.0"
      log.message.format.version: "3.0"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    resources: 
      requests:
        memory: 4Gi
        cpu:  1
      limits:
        memory: 4Gi
        cpu: 2
    jvmOptions: 
      -Xms: 4096m
      -Xmx: 4096m    
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}

